/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LR9If1YhKAl
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import FacebookPost from '@/lib/interfaces/firebase/FacebookPost';
import { ExternalLink } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';
import { formatDistanceToNow, format, isToday, isYesterday, differenceInDays } from 'date-fns';
import { pl } from 'date-fns/locale';

export function formatPolishDate(date: Date) {
    const now = new Date();
    const diffInDays = differenceInDays(now, date);

    if (isToday(date)) {
        return formatDistanceToNow(date, { locale: pl, addSuffix: true });
    } else if (isYesterday(date)) {
        return 'wczoraj';
    } else if (diffInDays < 7) {
        return formatDistanceToNow(date, { locale: pl, addSuffix: true });
    } else {
        return format(date, 'd MMMM yyyy', { locale: pl });
    }
}

export function FacebookCard({ imageUrl, link, timeCreated, text }: FacebookPost) {
    const date = new Date(timeCreated);

    return (
        <div className='rounded-lg border shadow-sm w-full'>
            <div className='flex flex-col items-start p-4'>
                <div className='flex w-full'>
                    <Avatar className='w-10 h-10 rounded-full mr-3'>
                        <AvatarImage src='/weeia_avatar.jpg' alt='WEEIA' />
                        <AvatarFallback>WEEIA</AvatarFallback>
                    </Avatar>
                    <div className='flex items-center justify-between w-full'>
                        <div>
                            <h3 className='font-semibold text-sm'>Wydział Elektrotechniki, Elektroniki, Informatyki i Automatyki PŁ</h3>
                            <p className='text-xs text-muted-foreground'>
                                <time dateTime={`${date}`}>{formatPolishDate(date)}</time>
                            </p>
                        </div>
                        <Link href={link} target='_blank' passHref>
                            <Button variant='ghost' size='icon' className='rounded-full'>
                                <ExternalLink />
                            </Button>
                        </Link>
                    </div>
                </div>
                <div className='flex flex-col'>
                    {text.split('\n').map((line, index) => (
                        <p key={index} className='text-sm mt-2'>
                            {line}
                        </p>
                    ))}
                </div>
            </div>
            <div className='w-full '>
                <Image
                    src={imageUrl}
                    alt='Post image'
                    width={800}
                    height={450}
                    className='object-cover w-full h-full rounded-b-lg'
                    style={{ objectFit: 'cover' }}
                />
            </div>
        </div>
    );
}
